version: "3"
services:
  video_editor:
    build: .
    image: "video_editor"
    container_name: "video_editor"
    working_dir: "/root/"
    env_file:
      - .env
    tty: true
    volumes:
      - ./src:/root/src
      - ./inputs:/root/inputs
      - ./outputs:/root/outputs
